---
title       : Practising slidify    
subtitle    : 
author      : Meenakshi Parameshwaran
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, landslide, Slidy ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap, shiny, interactive]
ext_widgets:: {rCharts: [libraries/nvd3]}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- .class #id 

## Making a list

- Something
- Something else
- Something else again

--- &radio

## Example quiz question

What is $x^2$ when $x$ is 9?

1. 89
2. 90
3. 99
4. _81_

*** .hint 
What is $9 \times 9$?

*** .explanation 
When $x$ is 9, $x^2$ is $9^2$, which is $9 \times 9$.

---

## Interactive chart - rCharts

```{r echo = F, results = 'asis'}
require(rCharts)
haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart',
  data = subset(haireye, Sex == 'Male')
)
n1$print('chart1')
```

--- &interactive
## Interactive console chart - google charts

Press the play button.

```{r opts.label = 'interactive', results = 'asis'}
require(googleVis)
M1 <- gvisMotionChart(Fruits, idvar = 'Fruit', timevar = 'Year')
print(M1, tag = 'chart')
```

---

## Interactive chart - Plot.Ly

```{r makeplotly, echo = FALSE, warning = FALSE}
#library(plotly)
#p1 <- plot_ly(midwest, x = percollege, color = state, type = "box")
# saveWidget(dplot, 'plotlyex1.html')
#htmlwidgets::saveWidget(as.widget(p1), "p1.html")
```

```{r showplotly, echo=FALSE, warning=FALSE, cache=FALSE, results='asis'}
cat('<iframe width="900" height="800" frameborder="0" scrolling="no" src="https://plot.ly/~mparam83/14.embed?share_key=jfRsrcGEtejXuix1Ej7fJi"></iframe>')
```


